### PR TITLE
Fix for issue #37

### PR DESCRIPTION
**Pull request by ramirost**
This PR fixes the issue #37 that can be reproduced when a job does not run the deploy phase.

### CODE REVIEW

**Comment by oliversalzburg** [comment]
Would be nice if anyone could confirm this.

**Comment by ramirost** [comment]
Of course is better than anybody else having the issue can test this but I can provide also more information to understand the fix.

When the a job is run without executing the deploy the phase object is something like this

captura de pantalla 2016-08-12 a las 10 40 33

The old code was checking always `exitCode` for deploy phase event when it was not executed and in such case `exitCode` was `-1`. The proposed fix only checks `exitCode` for deploy phase when finished is not null, which is determined by checking first for `finished!=null`

**Comment by oliversalzburg** [comment]
Alright. I'll merge this, but I can't `npm publish` as I lack the permissions :P

**Comment by ramirost** [comment]
Thanks, for us is ok if is included in the next release as we have version 1.4.2 patched locally.

**Comment by knownasilya** [comment]
@oliversalzburg I added you to npm for this one as well 👍

**Comment by knownasilya** [comment]
I added you to all the strider related repos I have access to, including gitane and dirkeeper.

**Comment by xyb** [comment]
@knownasilya, @oliversalzburg, maybe it's time to release new version?

**Comment by oliversalzburg** [comment]
Hmm, I just published 1.4.3. @knownasilya do we have a wiki article somewhere that describes the release process (we should)?

**Pull request merged**
