### PR TITLE
Feature/add pullrequest handling

### PR DESCRIPTION
**Pull request by nomean42**
Starting pull request update & pull request create jobs
Commenting on result of test and deploy

### CODE REVIEW

**Comment by knownasilya** [comment]
Could you explain a little more of what these changes do?

Also, could you squash your commits into a few distinct commits. Thanks!

**Comment by nomean42** [comment]
@knownasilya When strider-bitbucket get signal from [bitbucket hook](https://confluence.atlassian.com/bitbucket/pull-request-post-service-management-385913080.html), it starts a simple job like it already made for commit hooks.
Also here added a feature of sending test and deploy results. For commits its [Bitbucket Cloud](https://confluence.atlassian.com/bitbucket/integrate-your-build-system-with-bitbucket-cloud-790790968.html) [(issue)](https://github.com/Strider-CD/strider-bitbucket/issues/25).
For pull request it just a comment to pull request (e.g. ":star: SUCCESSFUL \<url to strider job\>")

**Comment by knownasilya** [comment]
This should help http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by nomean42** [comment]
@knownasilya Thank you for link, i tried to make commits look better

**Comment by knownasilya** [comment]
Excellent!

**Pull request merged**
